site_name: Raisa
site_url: https://raisa.jlnaufel.com
site_description: Raisa

theme:
    name: material
    palette:
    - scheme: default # Palette toggle for dark mode
      primary: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
    - scheme: pink # Palette toggle for light mode
      primary: white
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    features:
    - content.code.copy
    - navigation.top
    - navigation.instant

nav:
    - Home: 'index.md'
    - '03-03-25': '03-03-25.md'
    - '04-03-25': '04-03-25.md'
    - '05-03-25': '05-03-25.md'

extra:
  analytics:
    provider: google
    property: G-TGWJP6P18G

# -------------------------------------------------------------------
# Extensions: https://squidfunk.github.io/mkdocs-material/setup/extensions/
# -------------------------------------------------------------------
markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # Allow fences in fences and custom fences like mermaid diagrams
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

# -------------------------------------------------------------------
# Plugins: https://www.mkdocs.org/dev-guide/plugins/
# -------------------------------------------------------------------
plugins:
  - search
  - mermaid2
